#!/bin/zsh
set -e

LATEST='https://github.com/rems-project/pkvm-proxy-ocaml/raw/binaries/payload.tar.zst'

PAYLOAD_PATH=${0:A:h}/../payload
PAYLOAD_PATH=${PAYLOAD_PATH:a}

die() { echo $@ >&2; exit 1; }
type "curl" > /dev/null || die "ERROR: please install 'curl'."
tests=( $PAYLOAD_PATH/test_*(N) )
(( $#tests > 0 )) && die "ERROR: refusing to overwrite tests in $PAYLOAD_PATH"

curl -sL "$LATEST"|tar xvf - --zstd
