#!/bin/zsh

qemus=(
  '/usr/share/qemu'
  '/opt/homebrew/Cellar/qemu'
  "$HOME/.nix-profile/share/qemu"
  '/usr/local/share/qemu'
)

query='select(.targets[].architecture == "aarch64") |
       select(.features|all(. != "secure-boot")) |
       select(.mapping.device == "flash") |
       .mapping.executable.filename'

jq -r $query ${^qemus}/**/firmware/*.json(N) | tail -n1
